
if __name__ == '__main__':
    try:
        pass
    except Exception as e:
        print(f'An error has ocurred {e}')